version: '3.7'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - JAEGER_AGENT_HOST=jaeger
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.29
    ports:
      - "5775:5775"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14250:14250"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_HTTP_PORT=9411
